version: "3.7"

services:
  bot:
    image: node:14.15.1-buster
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
    working_dir: /app
    environment:
      ENV: development

    command: bash -c "npm start"
