version: "3.7"

services:
  bot-image:
    image: 036958288468.dkr.ecr.us-east-2.amazonaws.com/turntable/discord-bot:latest
    user: node
    volumes:
      - .:/app
      - ~/.aws:/home/node/.aws
    environment:
      AWS_REGION: us-east-2
      AWS_PROFILE: tt-staging
      DISCORD_BOT_SECRETS_PATH: /turntable/staging/bot-secrets
      ROOMS_SERVICE_API_BASE_URL: https://rooms.staging.tt.fm
      USER_SERVICE_API_BASE_URL: https://api.staging.tt.fm
