version: "3.7"

services:
  bot:
    image: node:16.6.0-buster
    user: node
    volumes:
      - .:/app
      - ~/.aws:/home/node/.aws
    working_dir: /app
    environment:
      AWS_REGION: us-east-2
      AWS_PROFILE: tt-staging
      DISCORD_BOT_SECRETS_PATH: /turntable/staging/jwt-secret
      ROOMS_SERVICE_API_BASE_URL: https://rooms.prod.tt.fm

    command: bash -c "npm start"
