name: Run tests on commit

on: [push]

env:
  NODE_VERSION: 16.13.1

jobs:
  bot_ci:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: "Use Node.js v${{ env.NODE_VERSION }}"
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install node dependencies
        run: npm i

      - name: "Test bot"
        run: npm run test

      - name: "Typecheck bot"
        run: npm run typecheck
